import { DataSet } from "./dataStore";

/* ═══════════════════════════════════════════════════════
   ACTION ENGINE — From Insight to Action
   Generates actionable buttons for each strategic finding.
   Closes the loop: see insight → take action → measure impact.
   ═══════════════════════════════════════════════════════ */

/* ── Types ────────────────────────────────────────── */
export interface ActionButton {
    id: string;
    label: string;
    icon: string;
    type: "export" | "drill_down" | "share" | "alert_rule";
    description: string;
    payload: Record<string, unknown>;
}

/* ── Generate Actions for a Finding ──────────────── */
export function generateActionsForFinding(
    finding: { insight: string; evidence: string; action: string; priority: string },
    dataset: DataSet,
    index: number,
): ActionButton[] {
    const actions: ActionButton[] = [];

    // 1. Drill Down — always available
    actions.push({
        id: `drill-${index}`,
        label: "Drill Down",
        icon: "🔍",
        type: "drill_down",
        description: `Ask a follow-up question about this finding`,
        payload: {
            question: finding.action.replace(/^(Investigate|Study|Analyze|Review|Check|Look into|Run)\s+/i, "Tell me more about "),
        },
    });

    // 2. Share — copy finding to clipboard
    actions.push({
        id: `share-${index}`,
        label: "Share",
        icon: "📋",
        type: "share",
        description: `Copy this insight to clipboard`,
        payload: {
            text: `📊 ${finding.insight}\n\n📈 Evidence: ${finding.evidence}\n\n→ ${finding.action}\n\n— Generated by alignd`,
        },
    });

    // 3. Export — export the relevant data
    actions.push({
        id: `export-${index}`,
        label: "Export CSV",
        icon: "↓",
        type: "export",
        description: `Download the data behind this finding`,
        payload: {
            columns: dataset.columns,
            rows: dataset.rows.slice(0, 1000), // cap for performance
        },
    });

    return actions;
}

/* ── Generate Actions for Recommendations ────────── */
export function generateActionsForRecommendation(
    recommendation: string,
    index: number,
): ActionButton[] {
    return [{
        id: `rec-drill-${index}`,
        label: "Investigate",
        icon: "→",
        type: "drill_down",
        description: `Run analysis on this recommendation`,
        payload: {
            question: recommendation,
        },
    }];
}

/* ── Execute Export Action ────────────────────────── */
export function executeExportAction(payload: { columns: string[]; rows: Record<string, string>[] }): string {
    const { columns, rows } = payload;

    const escapeCsvString = (val: string) => {
        const strVal = String(val ?? "");
        if (strVal.includes(",") || strVal.includes('"') || strVal.includes("\n") || strVal.includes("\r")) {
            return `"${strVal.replace(/"/g, '""')}"`;
        }
        return strVal;
    };

    const header = columns.map(escapeCsvString).join(",");
    const body = rows.map(row => columns.map(col => escapeCsvString(row[col])).join(",")).join("\n");
    return `${header}\n${body}`;
}
